service: lambda-config-demo

plugins:
 - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  versionFunctions: false

  iamRoleStatements:
    - Effect: 'Allow'
      Action: 'ssm:GetParameters'
      Resource: 
        - 'arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/foo'
        - 'arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/bar'
        - 'arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/jet'
        - 'arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/pack'
    # - Effect: 'Allow'
    #   Action: 'kms:Decrypt'
    #   Resource: 
        # change this to your KMS key
        # - 'arn:aws:kms:us-east-1:#{AWS::AccountId}:key/f66c6fbb-2c40-4ad5-8096-8512ed0733c5'

  # all the functions in the service will get these env variables
  environment:
    foo: foo

functions:
  withEnvVariable:
    handler: functions/withEnvVariable.handler
    environment:
      bar: bar

  # the same as the above, but uses Serverless's support for SSM Parameter Store
  withEnvVariable-SSM:
    handler: functions/withEnvVariable.handler
    environment:
      bar: ${ssm:bar~true} # true = decrypt it plz!

  withParamStore:
    handler: functions/withParamStore.handler

  withMiddleware:
    handler: functions/withMiddleware.handler